// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Artifact documents */
interface ArtifactDocumentData {
    /**
     * name field in *Artifact*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 成果物名
     * - **API ID Path**: artifact.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * description field in *Artifact*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 成果の詳細
     * - **API ID Path**: artifact.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * link field in *Artifact*
     *
     * - **Field Type**: Link
     * - **Placeholder**: 参照するリンク
     * - **API ID Path**: artifact.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * thumbnail field in *Artifact*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: artifact.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
}
/**
 * Artifact document from Prismic
 *
 * - **API ID**: `artifact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtifactDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ArtifactDocumentData>, "artifact", Lang>;
/** Content for Blog documents */
interface BlogDocumentData {
    /**
     * title field in *Blog*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 記事タイトル
     * - **API ID Path**: blog.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * thumbnail field in *Blog*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
    /**
     * description field in *Blog*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 概要
     * - **API ID Path**: blog.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Slice zone field in *Blog*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<BlogDocumentDataBodySlice>;
}
/**
 * Item in Blog → Slice zone → `linkcard_1` → Items
 *
 */
export interface BlogDocumentDataBodyLinkcard1SliceItem {
    /**
     * thumbnail field in *Blog → Slice zone → `linkcard_1` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.body[].linkcard_1.items[].thumbnail1
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail1: prismicT.ImageField<never>;
    /**
     * title field in *Blog → Slice zone → `linkcard_1` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: カードタイトル
     * - **API ID Path**: blog.body[].linkcard_1.items[].title1
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title1: prismicT.KeyTextField;
    /**
     * link field in *Blog → Slice zone → `linkcard_1` → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: カードをクリックした際の遷移先
     * - **API ID Path**: blog.body[].linkcard_1.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * color field in *Blog → Slice zone → `linkcard_1` → Items*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.body[].linkcard_1.items[].color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    color: prismicT.ColorField;
}
export type BlogDocumentDataBodyLinkcard1Slice = prismicT.Slice<"linkcard_1", Record<string, never>, Simplify<BlogDocumentDataBodyLinkcard1SliceItem>>;
/**
 * Primary content in Blog → Slice zone → `rich_editor` → Primary
 *
 */
interface BlogDocumentDataBodyRichEditorSlicePrimary {
    /**
     * rich_editor field in *Blog → Slice zone → `rich_editor` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.body[].rich_editor.primary.rich_editor
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    rich_editor: prismicT.RichTextField;
}
export type BlogDocumentDataBodyRichEditorSlice = prismicT.Slice<"rich_editor", Simplify<BlogDocumentDataBodyRichEditorSlicePrimary>, never>;
/**
 * Slice for *Blog → Slice zone*
 *
 */
type BlogDocumentDataBodySlice = BlogDocumentDataBodyLinkcard1Slice | BlogDocumentDataBodyRichEditorSlice;
/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;
/** Content for Blog documents */
interface BlogsDocumentData {
    /**
     * title field in *Blog*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 記事タイトル
     * - **API ID Path**: blogs.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * thumbnail field in *Blog*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blogs.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
    /**
     * description field in *Blog*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 概要
     * - **API ID Path**: blogs.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * contents field in *Blog*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogs.contents
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    contents: prismicT.RichTextField;
}
/**
 * Blog document from Prismic
 *
 * - **API ID**: `blogs`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogsDocumentData>, "blogs", Lang>;
/** Content for Career documents */
interface CareerDocumentData {
    /**
     * description field in *Career*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 何があったかを記載する
     * - **API ID Path**: career.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * date field in *Career*
     *
     * - **Field Type**: Date
     * - **Placeholder**: それが起きた日時
     * - **API ID Path**: career.date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    date: prismicT.DateField;
}
/**
 * Career document from Prismic
 *
 * - **API ID**: `career`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CareerDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CareerDocumentData>, "career", Lang>;
/** Content for News documents */
interface NewsDocumentData {
    /**
     * thumbnail field in *News*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: news.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
    /**
     * title field in *News*
     *
     * - **Field Type**: Text
     * - **Placeholder**: ニュースタイトル
     * - **API ID Path**: news.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *News*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 概要
     * - **API ID Path**: news.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * content field in *News*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: 詳細
     * - **API ID Path**: news.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;
/** Content for Skills documents */
interface SkillDocumentData {
    /**
     * name field in *Skills*
     *
     * - **Field Type**: Title
     * - **Placeholder**: スキル名
     * - **API ID Path**: skill.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * level field in *Skills*
     *
     * - **Field Type**: Number
     * - **Placeholder**: 1 ~ 10
     * - **API ID Path**: skill.level
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    level: prismicT.NumberField;
    /**
     * description field in *Skills*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 具体的な説明
     * - **API ID Path**: skill.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Skills document from Prismic
 *
 * - **API ID**: `skill`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<SkillDocumentData>, "skill", Lang>;
export type AllDocumentTypes = ArtifactDocument | BlogDocument | BlogsDocument | CareerDocument | NewsDocument | SkillDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ArtifactDocumentData, ArtifactDocument, BlogDocumentData, BlogDocumentDataBodyLinkcard1SliceItem, BlogDocumentDataBodyLinkcard1Slice, BlogDocumentDataBodyRichEditorSlicePrimary, BlogDocumentDataBodyRichEditorSlice, BlogDocumentDataBodySlice, BlogDocument, BlogsDocumentData, BlogsDocument, CareerDocumentData, CareerDocument, NewsDocumentData, NewsDocument, SkillDocumentData, SkillDocument, AllDocumentTypes };
    }
}
